# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(468, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QGraphicsView {\n"
"background-color: rgb(238, 240, 240);\n"
"}\n"
"\n"
"\n"
"QPushButton#updateButton {\n"
"border-top: 1px solid rgb(160, 160, 160);\n"
"border-bottom: 1px solid rgb(160, 160, 160);\n"
"border-right: 1px solid rgb(160, 160, 160);\n"
"}\n"
"\n"
"QPushButton#zoommButton {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-top-left-radius: 4px;\n"
"border-bottom-left-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#zoomrButton {\n"
"border-top: 1px solid rgb(160, 160, 160);\n"
"border-bottom: 1px solid rgb(160, 160, 160);\n"
"}\n"
"\n"
"QPushButton#zoompButton {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#connectButton {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-left: none;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"image: url(images/connect.png);\n"
"}\n"
"\n"
"QPushButton#connectButton:checked {\n"
"background-color: rgba(6, 192, 37, 40);\n"
"image: url(images/disconnect.png);\n"
"}\n"
"\n"
"QPushButton#runButton, QPushButton#clearButton {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#clearButton:pressed {\n"
"background-color: rgb(255, 200, 203);\n"
"}\n"
"\n"
"QPushButton#rotatelButton {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-top-left-radius: 4px;\n"
"border-bottom-left-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#rotaterButton {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-left: none;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(245, 245, 245);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(6, 192, 37, 40);\n"
"}\n"
"\n"
"\n"
"QComboBox {\n"
"border: 1px solid rgb(160, 160, 160);\n"
"border-top-left-radius: 4px;\n"
"border-bottom-left-radius: 4px;\n"
"padding-left: 7px;\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox::disabled {\n"
"border: 1px solid rgb(180, 180, 180);\n"
"border-top-left-radius: 4px;\n"
"border-bottom-left-radius: 4px;\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"background-color: rgb(243, 243, 243);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"background-color: rgba(6, 192, 37, 40);\n"
"}\n"
"\n"
"QComboBox::down-arrow:disabled {\n"
"image: url();\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"image: url(images/arrow-down.png);\n"
"width: 10px;\n"
"margin-right: 14px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"image: url(images/arrow-up.png);\n"
"width: 10px;\n"
"margin-right: 14px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"border: none;\n"
"selection-background-color: rgb(243, 243, 243);\n"
"height: 20px;\n"
"outline: 0px;\n"
"text-size: 12px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"border: none;\n"
"height: 36px;\n"
"text-size: 12px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover{\n"
"color:black;\n"
"}\n"
"\n"
"\n"
"QScrollBar {\n"
"background-color: rgb(238, 240, 240);\n"
"border: none;\n"
"}\n"
"\n"
"QComboBox QScrollBar {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"width: 10px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"height: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"background: none;\n"
"border: none;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"background-color: rgba(183, 183, 184, 180);\n"
"border-radius: 4px;\n"
"margin: 1px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"background-color: rgba(183, 183, 184, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 3, 4, 4)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.combobox = QtWidgets.QComboBox(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox.sizePolicy().hasHeightForWidth())
        self.combobox.setSizePolicy(sizePolicy)
        self.combobox.setMinimumSize(QtCore.QSize(152, 30))
        self.combobox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.combobox.setFont(font)
        self.combobox.setStyleSheet("")
        self.combobox.setObjectName("combobox")
        self.combobox.addItem("")
        self.horizontalLayout.addWidget(self.combobox)
        self.updateButton = QtWidgets.QPushButton(parent=self.widget)
        self.updateButton.setMinimumSize(QtCore.QSize(29, 30))
        self.updateButton.setMaximumSize(QtCore.QSize(29, 30))
        self.updateButton.setStyleSheet("")
        self.updateButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.updateButton.setIcon(icon1)
        self.updateButton.setIconSize(QtCore.QSize(20, 20))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.connectButton = QtWidgets.QPushButton(parent=self.widget)
        self.connectButton.setMinimumSize(QtCore.QSize(29, 30))
        self.connectButton.setMaximumSize(QtCore.QSize(30, 30))
        self.connectButton.setStyleSheet("")
        self.connectButton.setText("")
        self.connectButton.setIconSize(QtCore.QSize(20, 20))
        self.connectButton.setCheckable(True)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.rotatelButton = QtWidgets.QPushButton(parent=self.widget)
        self.rotatelButton.setMinimumSize(QtCore.QSize(30, 30))
        self.rotatelButton.setMaximumSize(QtCore.QSize(30, 30))
        self.rotatelButton.setStyleSheet("")
        self.rotatelButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/rotate l.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rotatelButton.setIcon(icon2)
        self.rotatelButton.setIconSize(QtCore.QSize(20, 20))
        self.rotatelButton.setObjectName("rotatelButton")
        self.horizontalLayout.addWidget(self.rotatelButton)
        self.rotaterButton = QtWidgets.QPushButton(parent=self.widget)
        self.rotaterButton.setMinimumSize(QtCore.QSize(29, 30))
        self.rotaterButton.setMaximumSize(QtCore.QSize(30, 30))
        self.rotaterButton.setStyleSheet("")
        self.rotaterButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/rotate r.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rotaterButton.setIcon(icon3)
        self.rotaterButton.setIconSize(QtCore.QSize(20, 20))
        self.rotaterButton.setObjectName("rotaterButton")
        self.horizontalLayout.addWidget(self.rotaterButton)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.runButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(30, 30))
        self.runButton.setMaximumSize(QtCore.QSize(30, 30))
        self.runButton.setStyleSheet("")
        self.runButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.runButton.setIcon(icon4)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.clearButton = QtWidgets.QPushButton(parent=self.widget)
        self.clearButton.setMinimumSize(QtCore.QSize(30, 30))
        self.clearButton.setMaximumSize(QtCore.QSize(30, 30))
        self.clearButton.setStyleSheet("")
        self.clearButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clearButton.setIcon(icon5)
        self.clearButton.setIconSize(QtCore.QSize(14, 14))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem4 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.zoommButton = QtWidgets.QPushButton(parent=self.widget)
        self.zoommButton.setMinimumSize(QtCore.QSize(30, 30))
        self.zoommButton.setMaximumSize(QtCore.QSize(30, 30))
        self.zoommButton.setStyleSheet("")
        self.zoommButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/zoom-.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.zoommButton.setIcon(icon6)
        self.zoommButton.setIconSize(QtCore.QSize(20, 20))
        self.zoommButton.setObjectName("zoommButton")
        self.horizontalLayout.addWidget(self.zoommButton)
        self.zoomrButton = QtWidgets.QPushButton(parent=self.widget)
        self.zoomrButton.setMinimumSize(QtCore.QSize(30, 30))
        self.zoomrButton.setMaximumSize(QtCore.QSize(30, 30))
        self.zoomrButton.setStyleSheet("")
        self.zoomrButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/zoom=.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.zoomrButton.setIcon(icon7)
        self.zoomrButton.setIconSize(QtCore.QSize(20, 20))
        self.zoomrButton.setObjectName("zoomrButton")
        self.horizontalLayout.addWidget(self.zoomrButton)
        self.zoompButton = QtWidgets.QPushButton(parent=self.widget)
        self.zoompButton.setMinimumSize(QtCore.QSize(30, 30))
        self.zoompButton.setMaximumSize(QtCore.QSize(30, 30))
        self.zoompButton.setStyleSheet("")
        self.zoompButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/zoom+.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.zoompButton.setIcon(icon8)
        self.zoompButton.setIconSize(QtCore.QSize(20, 20))
        self.zoompButton.setObjectName("zoompButton")
        self.horizontalLayout.addWidget(self.zoompButton)
        self.verticalLayout.addWidget(self.widget)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setStyleSheet("")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Locator viewer 1.0"))
        self.combobox.setToolTip(_translate("MainWindow", "Порт устройства"))
        self.combobox.setItemText(0, _translate("MainWindow", "Портов не найдено"))
        self.updateButton.setToolTip(_translate("MainWindow", "Обновить список портов"))
        self.connectButton.setToolTip(_translate("MainWindow", "Подключиться"))
        self.rotatelButton.setToolTip(_translate("MainWindow", "Повернуть влево"))
        self.rotaterButton.setToolTip(_translate("MainWindow", "Повернуть вправо"))
        self.runButton.setToolTip(_translate("MainWindow", "Начать сканирование"))
        self.clearButton.setToolTip(_translate("MainWindow", "Очистить вывод"))
        self.zoommButton.setToolTip(_translate("MainWindow", "Уменьшить масштаб"))
        self.zoomrButton.setToolTip(_translate("MainWindow", "Сбросить масштаб"))
        self.zoompButton.setToolTip(_translate("MainWindow", "Увеличить масштаб"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
